/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RankingFrame.java
 *
 * Created on Jan 22, 2010, 7:41:14 PM
 */

package crickinfo;

import java.sql.*;
import javax.swing.*;
/**
 *
 * @author darkdevs
 */
public class RankingFrame extends javax.swing.JFrame {

    Connection con;
    Statement st;
    ResultSet rs;

    /** Creates new form RankingFrame */
    public RankingFrame() {
        initComponents();
        try{
            con = DriverManager.getConnection("jdbc:odbc:blazers");
            st = con.createStatement();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.toString());
        }
        showRanking();
    }

    public void showRanking()
    {
        String sql="select name,team,pts from RankElim";
        String s="";
        int i=1;
        try{
            rs = st.executeQuery(sql);

            s="<table width=100% border=1>" +
                  "<th>Rank</th><th>Name</th><th>Team</th><th>Points</th>";
            while(rs.next())
            {
                s=s+"<tr>";
                s=s+"<td>"+i+"</td>";
                s=s+"<td width=35%>"+rs.getString("name")+"</td>";
                s=s+"<td width=35%>"+rs.getString("team")+"</td>";
                s=s+"<td>"+rs.getString("pts")+"</td>";
                s=s+"</tr>";
                i++;
            }
            s=s+"</font></table>";
            jScrollPane1.repaint();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, e.toString());
        }
        view.setText(s);
    }

    public void showBatting()
    {
        String sql="select name,team,runs,batavg,stkrate from Ranking where runs > 0 order by runs desc";
        String s="";
        int i=1;
        try{
            rs = st.executeQuery(sql);

            s="<table width=100% border=1>" +
                  "<th>Rank</th><th>Name</th><th>Team</th><th>Runs</th><th>Average</th><th>Strike Rate</th>";
            while(rs.next())
            {
                s=s+"<tr>";
                s=s+"<td>"+i+"</td>";
                s=s+"<td width=35%>"+rs.getString("name")+"</td>";
                s=s+"<td width=35%>"+rs.getString("team")+"</td>";
                s=s+"<td>"+rs.getString("runs")+"</td>";
                s=s+"<td>"+rs.getString("batavg")+"</td>";
                s=s+"<td>"+rs.getString("stkrate")+"</td>";
                s=s+"</tr>";
                i++;
            }
            s=s+"</font></table>";
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, e.toString());
        }
        view.setText(s);
    }

    public void showBowling()
    {
        String sql="select name,team,wkts,ecorate from Ranking where wkts>0 order by wkts desc";
        String s="";
        int i=1;
        try{
            rs = st.executeQuery(sql);

            s="<table width=100% border=1>" +
                  "<th>Rank</th><th>Name</th><th>Team</th><th>Wickets</th><th>Economy Rate</th>";
            while(rs.next())
            {
                s=s+"<tr>";
                s=s+"<td>"+i+"</td>";
                s=s+"<td width=35%>"+rs.getString("name")+"</td>";
                s=s+"<td width=35%>"+rs.getString("team")+"</td>";
                s=s+"<td>"+rs.getString("wkts")+"</td>";
                s=s+"<td>"+rs.getString("ecorate")+"</td>";
                s=s+"</tr>";
                i++;
            }
            s=s+"</table>";
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, e.toString());
        }
        view.setText(s);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        tournTog = new javax.swing.JToggleButton();
        batTog = new javax.swing.JToggleButton();
        bowlTog = new javax.swing.JToggleButton();

        buttonGroup1.add(tournTog);
        buttonGroup1.add(batTog);
        buttonGroup1.add(bowlTog);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Players Ranking");

        view.setContentType("text/html");
        jScrollPane1.setViewportView(view);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tournTog.setSelected(true);
        tournTog.setText("Tournament Ranking");
        tournTog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tournTogActionPerformed(evt);
            }
        });
        jPanel1.add(tournTog);

        batTog.setText("Batting");
        batTog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batTogActionPerformed(evt);
            }
        });
        jPanel1.add(batTog);

        bowlTog.setText("Bowling");
        bowlTog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowlTogActionPerformed(evt);
            }
        });
        jPanel1.add(bowlTog);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tournTogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tournTogActionPerformed
        // TODO add your handling code here:
        showRanking();
    }//GEN-LAST:event_tournTogActionPerformed

    private void batTogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batTogActionPerformed
        // TODO add your handling code here:
        showBatting();
    }//GEN-LAST:event_batTogActionPerformed

    private void bowlTogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowlTogActionPerformed
        // TODO add your handling code here:
        showBowling();
    }//GEN-LAST:event_bowlTogActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton batTog;
    private javax.swing.JToggleButton bowlTog;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton tournTog;
    private javax.swing.JEditorPane view;
    // End of variables declaration//GEN-END:variables

}
